name: Compile playlists from YouTube

on:
  # schedule:
  #   - cron: "0 0 * * *"
  push:
    branches:
      - youtube-cron

jobs:
  build:
    name: Compile playlists from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            youtube-data
      - name: Access cloned repository content
        run: cd youtube-data && ls -al

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'youtube-data/package-lock.json'
      - name: Install dependencies
        run: npm install